default_platform(:android)

def is_pre_release_ref(ref_name)
  # Determine pre-release from tag/branch name
  return ref_name =~ /v?(\d|.)+-([a-z]+)\d*/ ? true : false
end

platform :android do
  # ==========================
  # Lane for build artifact
  # ==========================
  desc "Build APK and zip entire outputs folder for GitHub Actions"
  lane :artifact_zip do |options|
  ref_name = options[:ref_name] || "manual_build"
  is_pre_release = is_pre_release_ref(ref_name)

  # Determine variant and build
  if is_pre_release
    gradle(tasks: ["clean", "app:assembleFossBetaRelease"], flags: "--no-daemon --stacktrace")
    apk_path = Dir["app/build/outputs/apk/fossBeta/release/*.apk"].first
  else
    gradle(tasks: ["clean", "app:assembleFossProductRelease"], flags: "--no-daemon --stacktrace")
    apk_path = Dir["app/build/outputs/apk/fossProduct/release/*.apk"].first
  end

  # Optional: just for information, won't cause errors
  if apk_path.nil? || !File.exist?(apk_path)
    puts "⚠️ APK not found, but continue..."
  else
    puts "✅ APK built: #{apk_path}"
  end

  # ==========================
  # Lane for Github Release (optional)
  # ==========================
  desc "Deploy to Github release (optional)"
  lane :release do |options|
    if ENV["GITHUB_TOKEN"].nil? && ENV["GITHUB_API_TOKEN"].nil?
      puts "⚠️ GITHUB_TOKEN env and GITHUB_API_TOKEN env not found, skip!"
      next
   end

    ref_name = options[:ref_name]
    UI.user_error!("⚠️ github.ref_name not provided") if ref_name.nil?

    is_pre_release = is_pre_release_ref(ref_name)

    # Build APK according to variant
    if is_pre_release
      gradle(tasks: ["clean", "app:assembleFossBetaRelease"], flags: "--no-daemon --stacktrace")
      apk_path = Dir["app/build/outputs/apk/fossBeta/release/*.apk"].first
    else
      gradle(tasks: ["clean", "app:assembleFossProductRelease"], flags: "--no-daemon --stacktrace")
      apk_path = Dir["app/build/outputs/apk/fossProduct/release/*.apk"].first
    end

    # mapping.txt
    mapping_path = lane_context[SharedValues::GRADLE_MAPPING_TXT_OUTPUT_PATH]
    mapping_dir = File.dirname(mapping_path)
    mapping_zip = File.join(mapping_dir, "mapping.zip")
    Dir.chdir(mapping_dir) do
      sh("zip", "mapping.zip", File.basename(mapping_path))
    end

    # Upload to GitHub Release
    set_github_release(
      repository_name: "kqkqku86-a11y/AndroidEasterEggs",
      api_bearer: ENV["GITHUB_TOKEN"],
      is_prerelease: is_pre_release,
      name: ref_name,
      tag_name: ref_name,
      description: "Release APK",
      upload_assets: [apk_path, mapping_zip],
    )

    puts "✅ GitHub Release created for #{ref_name}"
  end
end
