default_platform(:android)

def is_pre_release_ref(ref_name)
  if (ref_name =~ /v?(\d|.)+-([a-z]+)\d*/)
    return true
  else
    return false
  end
end

platform :android do
  # ==========================
  # Lane untuk build artifact
  # ==========================
  desc "Build APK for GitHub Actions Artifact"
  lane :artifact do |options|
    # Build release APK (tanpa upload ke Pgyer)
    ref_name = options[:ref_name] || "manual_build"
    is_pre_release = is_pre_release_ref(ref_name)

    if is_pre_release
      gradle(tasks: ["clean", "app:assembleFossBetaRelease"], flags: "--no-daemon --stacktrace")
    else
      gradle(tasks: ["clean", "app:assembleFossProductRelease"], flags: "--no-daemon --stacktrace")
    end

    # Ambil path APK agar bisa diupload ke GitHub artifact
    apk_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    if apk_path.nil? || !File.exist?(apk_path) || !File.file?(apk_path)
      UI.user_error!("⚠️ GRADLE_APK_OUTPUT_PATH not found!")
    else
      puts "✅ APK ready at #{apk_path}"
    end
  end

  # ==========================
  # Lane untuk GitHub Release
  # ==========================
  desc "Deploy to Github release (optional)"
  lane :release do |options|
    if ENV["GITHUB_TOKEN"].nil? && ENV["GITHUB_API_TOKEN"].nil?
      puts "⚠️ GITHUB_TOKEN env and GITHUB_API_TOKEN env not found, skip!"
      next
    end

    ref_name = options[:ref_name]
    if ref_name.nil?
      puts "⚠️ github.ref_name not found, skip!"
      next
    end

    is_pre_release = is_pre_release_ref(ref_name)
    if is_pre_release
      gradle(tasks: ["clean", "app:assembleFossBetaRelease"])
    else
      gradle(tasks: ["clean", "app:assembleFossProductRelease"])
    end

    apk_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    mapping_path = lane_context[SharedValues::GRADLE_MAPPING_TXT_OUTPUT_PATH]

    mapping_dir = File.dirname(mapping_path)
    mapping_zip = File.join(mapping_dir, "mapping.zip")
    Dir.chdir(mapping_dir) do
      sh("zip", "mapping.zip", File.basename(mapping_path))
    end

    github_release = set_github_release(
      repository_name: "hushenghao/AndroidEasterEggs",
      api_bearer: ENV["GITHUB_TOKEN"],
      is_prerelease: is_pre_release,
      name: ref_name,
      tag_name: ref_name,
      description: "Release APK",
      upload_assets: [apk_path, mapping_zip],
    )
  end
end
